### ISSUE TITLE
getPhotoForId crash on iOS

### ISSUE THREAD

**Issue by bourgois** [rt2zz/react-native-contacts#136]
Hi

In the mean time we were trying to use the getPhotoForId function on iOS.
We added the following code:
```
      Contacts.getPhotoForId(contactList[i].recordID, (err, result) => {
                   if (result != '') { console.log(' PATH RESULT : ',result); }     
     });
```
It does display path but on a real device with 3000 contacts, it often endup with a crash and the following error:
```
AB: Could not compile statement for query (ABCCopyArrayOfAllInstancesOfClassInSourceMatchingPredicates):
SELECT ROWID, Name, ExternalIdentifier, Type, ConstraintsPath, ExternalModificationTag, ExternalSyncTag, AccountID, Enabled, SyncData, MeIdentifier, Capabilities FROM ABStore WHERE Enabled = ?;
```
And sometime:
```
[error][tid:com.facebook.react.ContactsQueue][RCTConvert.m:59] JSON value '1' of type NSString cannot be converted to NSNumber
```
:(

**Comment by npomfret** [comment]
@tszajna0 do you have any idea why this is happening?  Seems to have been introduced when we merged the change to add `getPhotoForId`.

**Comment by npomfret** [comment]
Could you try the changes on my fork https://github.com/npomfret/react-native-contacts?  I'm using the new contacts api, maybe it doesn't suffer from this issue.

**Comment by bourgois** [comment]
Hi @npomfret 

I get the following fatal crash with this version:

[tid:com.facebook.react.ContactsQueue] Exception '-[__NSCFNumber stringByReplacingOccurrencesOfString:withString:]: unrecognized selector sent to instance 0x10e7cc830' was thrown while invoking getPhotoForId on target Contacts with params (
    nan,
    31
)

Did you made some changes in the way getPhotoForId works that would require me to make changes in my previous code?

Thanks for all the help!

**Comment by bourgois** [comment]
Hi @npomfret 
Unfortunately it still doesn't work.

Today, with the current production code, on a iphone 6+, ios 9.3.3 with 3000 contacts, my function that use the getall with thumbnails takes around 17s:
```
Get All Contact (time elapsed): 17769
Get All Contact (time elapsed): 16399
Get All Contact (time elapsed): 16567
Get All Contact (time elapsed): 16662
Get All Contact (time elapsed): 16816
```

- If I just add the following code (keeping 0.7.1):

```
Contacts.getPhotoForId(Number.parseInt(contactList[i].recordID,10), (err, result) => {
             if (result != '') {
             console.log(' err : ',err);
             console.log(' PATH RESULT : ',result);
             console.log(' contactList[i].recordID :' , contactList[i].recordID);
             let paththumb = result;
}
 });

  }
}
}
```

I get a first getall in around 17s but after that it goes banana...
```
Get All Contact (time elapsed): 18548
```
The getPhotoForId is called after this 1st getall generates the following errors:

We get those errors:
```
AB: Could not compile statement for query (ABCCopyArrayOfAllInstancesOfClassInSourceMatchingPredicates):
SELECT ROWID, Name, ExternalIdentifier, Type, ConstraintsPath, ExternalModificationTag, ExternalSyncTag, AccountID, Enabled, SyncData, MeIdentifier, Capabilities FROM ABStore WHERE Enabled = ?;
AB: Could not compile statement for query (ABCCopyArrayOfAllInstancesOfClassInSourceMatchingPredicates):
SELECT ROWID, Name, ExternalIdentifier, Type, ConstraintsPath, ExternalModificationTag, ExternalSyncTag, AccountID, Enabled, SyncData, MeIdentifier, Capabilities FROM ABStore WHERE Enabled = ?;
```
```
Unknown error calling sqlite3_step (14: unable to open database file) eu
DB Query: UPDATE info SET next_header_number = (next_header_number + 1)
Unknown error finalizing or resetting statement (14: unable to open database file)
DB Query: UPDATE info SET next_header_number = (next_header_number + 1)
```
```
Critical failure: the LastResort font is unavailable.
CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

Resulting in the next getall call to last for ever:
```
Get All Contact (time elapsed): 246545
```

- With new version from npomfret:

I still have the first getall in around 17s:
Get All Contact (time elapsed): 18611

But next one is 407s:
Get All Contact (time elapsed): 407175

And I have the same types of errors:
```
Critical failure: the LastResort font is unavailable.
CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

AB: Could not compile statement for query (ABCCopyArrayOfAllInstancesOfClassInSourceMatchingPredicates):
SELECT ROWID, Name, ExternalIdentifier, Type, ConstraintsPath, ExternalModificationTag, ExternalSyncTag, AccountID, Enabled, SyncData, MeIdentifier, Capabilities FROM ABStore WHERE Enabled = ?;
Unknown error calling sqlite3_step (14: unable to open database file) eu
DB Query: UPDATE info SET next_header_number = (next_header_number + 1)
Unknown error finalizing or resetting statement (14: unable to open database file)
```

**Comment by npomfret** [comment]
Thanks @bourgois - these errors are from my branch, yes?

**Comment by bourgois** [comment]
Yes @npomfret the last bullet point is with your fork :(
Seems pretty much the same that the current version!

What is really strange is the part about LastResort Font and CG_CONTEXT_SHOW_BACKTRACE, I couldn't find anything related to that in the code...

For the AB error, I could find a few people complaining about that when making many requests to iOS AB and the answer was 'try using the AB less'... not really an option in my use case.
Still, there are plenty of AB related apps so there should be a way to access the AB without issues.
I was thinking about asking Brent Vatne as I know he developed a list view specifically because he had issues displaying very large AB, but he never mentioned issues with accessing the AB...

**Comment by npomfret** [comment]
That's strange. My branch doesn't use the _AB..._ api.

**Comment by npomfret** [comment]
ok, i've updated my fork so that all methods use the new iOS api.  And there's a test suite [here](https://github.com/morenoh149/react-native-contacts-test) that now has a load test.  It's quite slow, largely because adding contacts is slow, so be patient.  And you need to point it at my fork...

I've tried to use it to reproduce the error you're seeing but so far I've not managed to see the error.

Is it possible you're making many calls to `getPhotoForId` in parallel and just overloading the phone?

**Comment by bourgois** [comment]
Hi @npomfret , I tried to test your updated fork but got the following error:

`[fatal][tid:com.facebook.react.ContactsQueue] Exception '*** setObjectForKey: object cannot be nil (key: label)' was thrown while invoking getAll on target Contacts with params (
    1
)`
I had a quick look at your code and I wonder if you don't have an issue in this part in case there is no label:
`        if(type) {
             [email setObject: [labeledValue value] forKey:@"email"];
             [email setObject: type forKey:@"label"];
             [emailAddreses addObject:email];
        }`

But indeed, I could be overloading the phone as the getPhotoForId is in a "for loop" that looks at all the contacts and it is called asynchronously... I will think about how I could wait for the getPhotoForId before the "for" move to the next iteration and test that.

Thanks again for your support!

**Comment by npomfret** [comment]
Thanks for the feedback.  I had the same issue and it was to do with a contact that had a phone number or email address which had no label.  I'll put some code in to guard against it.

WRT over loading the device with calls, the test project works around this by effectively single threading the calls to the native code [here](https://github.com/morenoh149/react-native-contacts-test/blob/master/src/RNContactsTest.js#L266).  Its not ideal as the device can handle more than one at once.

**Comment by npomfret** [comment]
@bourgois - could you try my fork once more please?  I've added some code to guard against empty labels or values

**Comment by bourgois** [comment]
@npomfret 
thanks, it resolve the label issue...

So now, I can run again my original code, with no issue. 
In fact it is already much faster than with the current production branch: 3s instead of 17s ! 🥇 

But if I try again to put my getPhotoForId code, I get those two types of errors:
'
[RCTConvert.m:58] JSON value 'nan' of type NSNumber cannot be converted to NSString
[RCTConvert.m:58] JSON value '91' of type NSNumber cannot be converted to NSString
....
'

'
[RCTModuleMethod.m:57] Argument 0 (nan) of Contacts. could not be processed. Aborting method call.
[RCTModuleMethod.m:57] Argument 0 (0) of Contacts. could not be processed. Aborting method call.
[RCTModuleMethod.m:57] Argument 0 (66692) of Contacts. could not be processed. Aborting method call.
....
'

With the getAllWithoutPhotos I only get down to 1.6s so using your version of getAll is already quite an improvement! I will still explore a little next week the benefit of getAllWithoutPhotos with getPhotoForId if I put that in a loop that is less at risk of overloading the phone, but it requires some changes in our logic so not super simple to implement...

In any case, I would suggest pushing to @rt2zz a PR with the changes as it does improve greatly the basic GetAll and my getPhotoForId issues is present in both and seems less problematic in this version.

Thanks a lot!!

**Comment by bourgois** [comment]
@npomfret I am not good at all with objC but I was wondering if this could be something helpful for your code:
[ABAddressBookRef issue](http://stackoverflow.com/questions/14010320/abaddressbookcreate-abaddressbookgetgroupcount-return-0x00000000-ni)

This is the relevant part:
```
Why are you not tring to minimize number of time you create and access the ABAddressBookRef by using the following :

void ABAddressBookRegisterExternalChangeCallback (
   ABAddressBookRef addressBook,
   ABExternalChangeCallback callback,
   void *context
);
this allow to your app know when the addressBook get modify by external. and to let you know that you need to re-access the address-book.

The same thing for your method that you post it, every time you call it will create new object with new access to address book
```

**Comment by npomfret** [comment]
@bourgois thanks again for your feedback.  It's good that you have an address book with lots of badly formatted fields, very useful.

The new code does't use `ABAddressBookRef`.  Instead it uses `CNContactStore`.  I tried only creating one instance of it (which is the current implementation) to see if it was quicker than creating a new instance each time, but it didn't seem to make any difference to performance.

**Comment by npomfret** [comment]
@bourgois 

WRT these errors:

```
[RCTConvert.m:58] JSON value 'nan' of type NSNumber cannot be converted to NSString
[RCTConvert.m:58] JSON value '91' of type NSNumber cannot be converted to NSString
....
[RCTModuleMethod.m:57] Argument 0 (nan) of Contacts. could not be processed. Aborting method call.
[RCTModuleMethod.m:57] Argument 0 (0) of Contacts. could not be processed. Aborting method call.
[RCTModuleMethod.m:57] Argument 0 (66692) of Contacts. could not be processed. Aborting method call.
```

Which method call produced them?  And did they result in your app crashing?

**Comment by bourgois** [comment]
@npomfret 

This is due to my `Contacts.getPhotoForId(Number.parseInt(contactList[i].recordID,10)` call.

In debug I can dismiss and keep using the app but I get a bunch of:
```
[error][tid:com.facebook.react.ContactsQueue][RCTModuleMethod.m:57] Argument 0 (299) of Contacts. could not be processed. Aborting method call.
[error][tid:com.facebook.react.ContactsQueue][RCTConvert.m:58] JSON value '299' of type NSNumber cannot be converted to NSString
```

In release mode it crash with :
```
[fatal][tid:com.facebook.react.ContactsQueue] Exception '-[__NSCFNumber stringByReplacingOccurrencesOfString:withString:]: unrecognized selector sent to instance 0x1acda6130' was thrown while invoking getPhotoForId on target Contacts with params (
    nan,
    23
)
```

**Comment by bourgois** [comment]
@npomfret 
Ok. Found the issue but don't really understand why...

It seemed to be an issue between NSNumber needing to be converted in NSString.

I had the issue the other way around which is why I used Number.parseInt(contactList[i].recordID,10) for the getPhotoForId inpput.

Now if I move back to just using contactList[i].recordID as input... it works !

**Comment by npomfret** [comment]
The record ids should not be treated as ints, they aren't numeric.

**Comment by bourgois** [comment]
Indeed! But getPhotoForId used to take an NSNumber (cf :
https://github.com/rt2zz/react-native-contacts/blob/5f762d3bf18ab716523cb1308565dfe9c19a7d00/ios/RCTContacts/RCTContacts.m )
it was corrected at some point and now takes an NSString... but I didn't realised and kept my code to change the RecordID into a number as input to getPhotoForId.
All good now :)
Thanks a lot for all your support.
